/**
 * FORMA Elite Exercise Library — data only (no logic).
 * Volume 1: exercises 1–52. Volume 2: exercises 53–102.
 * Supersets: Volume 4 catalog SS1–SS60.
 */

export const EXERCISE_LIBRARY = {
  1: {
    id: 1,
    name: 'Barbell Back Squat',
    section: 'Lower Body Strength',
    equipment: ['barbell'],
    musclesWorked: ['quads', 'glutes', 'hamstrings'],
    coachingCues: 'Bar on mid-traps, brace core, knees track toes, chest up, drive through floor',
    progression: 'Pause squat 3 seconds at bottom',
    regression: 'Goblet squat or box squat',
    experienceLevel: 'intermediate',
    movementPattern: 'squat',
  },
  2: {
    id: 2,
    name: 'Barbell Romanian Deadlift',
    section: 'Lower Body Hinge',
    equipment: ['barbell'],
    musclesWorked: ['hamstrings', 'glutes', 'erectors'],
    coachingCues: 'Hinge at hip not squat, bar drags down thighs, soft knee bend, feel hamstring stretch, drive hips forward',
    progression: 'Deficit RDL or 2 second pause at max hamstring tension',
    regression: 'Single leg dumbbell RDL or pull through with band',
    experienceLevel: 'intermediate',
    movementPattern: 'hinge',
  },
  3: {
    id: 3,
    name: 'Barbell Front Squat',
    section: 'Lower Body Strength',
    equipment: ['barbell'],
    musclesWorked: ['quads', 'glutes', 'core'],
    coachingCues: 'Clean grip or crossed arm, elbows high non-negotiable, bar on front deltoids, more upright than back squat',
    progression: 'Overhead squat or Zercher squat',
    regression: 'Goblet squat',
    experienceLevel: 'advanced',
    movementPattern: 'squat',
  },
  4: {
    id: 4,
    name: 'Barbell Hip Thrust',
    section: 'Lower Body Hinge',
    equipment: ['barbell', 'bench'],
    musclesWorked: ['glutes', 'hamstrings'],
    coachingCues: 'Shoulders on bench, bar padded across hips, drive to full extension, squeeze glutes hard, no hyperextension',
    progression: 'Single leg barbell hip thrust or banded variation',
    regression: 'Bodyweight glute bridge',
    experienceLevel: 'intermediate',
    movementPattern: 'hinge',
  },
  5: {
    id: 5,
    name: 'Barbell Sumo Deadlift',
    section: 'Lower Body Hinge',
    equipment: ['barbell'],
    musclesWorked: ['hamstrings', 'glutes', 'adductors'],
    coachingCues: 'Wide stance toes out 30 to 45 degrees, grip inside legs, push floor apart, hips drop lower than conventional',
    progression: 'Conventional deadlift or trap bar deadlift',
    regression: 'Kettlebell sumo deadlift',
    experienceLevel: 'advanced',
    movementPattern: 'hinge',
  },
  6: {
    id: 6,
    name: 'Dumbbell Bulgarian Split Squat',
    section: 'Lower Body Unilateral',
    equipment: ['dumbbells', 'bench'],
    musclesWorked: ['quads', 'glutes', 'hip flexors'],
    coachingCues: 'Rear foot elevated, front foot far enough forward for vertical shin, knee drops straight down',
    progression: 'Deficit split squat or goblet hold',
    regression: 'Bodyweight split squat no elevation',
    experienceLevel: 'intermediate',
    movementPattern: 'squat',
  },
  7: {
    id: 7,
    name: 'Dumbbell Walking Lunge',
    section: 'Lower Body Unilateral',
    equipment: ['dumbbells'],
    musclesWorked: ['quads', 'glutes', 'hamstrings'],
    coachingCues: '90-90 angle both knees, drive through front heel, torso upright, alternate legs',
    progression: 'Barbell walking lunge or overhead lunge',
    regression: 'Reverse lunge in place',
    experienceLevel: 'beginner',
    movementPattern: 'squat',
  },
  8: {
    id: 8,
    name: 'Dumbbell Step Up',
    section: 'Lower Body Unilateral',
    equipment: ['dumbbells', 'box'],
    musclesWorked: ['quads', 'glutes'],
    coachingCues: 'Box high enough for parallel thigh, drive through heel of working leg, no push off back foot',
    progression: 'Weighted vest step up with knee drive or lateral step up',
    regression: 'Bodyweight step up low box',
    experienceLevel: 'beginner',
    movementPattern: 'squat',
  },
  9: {
    id: 9,
    name: 'Dumbbell Goblet Squat',
    section: 'Lower Body Strength',
    equipment: ['dumbbells'],
    musclesWorked: ['quads', 'glutes', 'adductors', 'core'],
    coachingCues: 'Hold dumbbell vertically at chest, feet shoulder width slight toe out, sit between knees, elbows inside knees at bottom',
    progression: 'Front rack dumbbell squat or 3 second pause',
    regression: 'Bodyweight squat to box',
    experienceLevel: 'beginner',
    movementPattern: 'squat',
  },
  10: {
    id: 10,
    name: 'Dumbbell Lateral Lunge',
    section: 'Lower Body Unilateral',
    equipment: ['dumbbells'],
    musclesWorked: ['adductors', 'glutes', 'quads'],
    coachingCues: 'Step wide to one side, sit back into hip of working leg, non-working leg straight, chest tall',
    progression: 'Cossack squat or dumbbell reach to opposite foot',
    regression: 'Bodyweight side to side lunge',
    experienceLevel: 'beginner',
    movementPattern: 'squat',
  },
  11: {
    id: 11,
    name: 'Kettlebell Swing Two Hand',
    section: 'Lower Body Power',
    equipment: ['kettlebell'],
    musclesWorked: ['glutes', 'hamstrings', 'erectors'],
    coachingCues: 'Hip hinge NOT squat, hike bell back aggressively, snap hips forward, squeeze glutes and quads, bell floats to chest from hip drive alone',
    progression: 'Single arm swing or alternating hand switch',
    regression: 'Kettlebell deadlift',
    experienceLevel: 'intermediate',
    movementPattern: 'hinge',
  },
  12: {
    id: 12,
    name: 'Kettlebell Goblet Squat Plus Pulse',
    section: 'Lower Body Strength',
    equipment: ['kettlebell'],
    musclesWorked: ['quads', 'glutes', 'adductors'],
    coachingCues: 'Hold KB by horns at chest, squat deep, 3 small pulses at bottom before standing',
    progression: 'KB front rack squat or KB overhead squat',
    regression: 'Bodyweight goblet squat holding horns for counterbalance',
    experienceLevel: 'beginner',
    movementPattern: 'squat',
  },
  13: {
    id: 13,
    name: 'Kettlebell Romanian Deadlift Single Leg',
    section: 'Lower Body Unilateral',
    equipment: ['kettlebell'],
    musclesWorked: ['hamstrings', 'glutes', 'erectors'],
    coachingCues: 'Hold KB in opposite hand to working leg, hip hinge back and down, non-working leg extends behind, flat back',
    progression: 'Barbell single leg RDL or ipsilateral KB',
    regression: 'Two leg KB RDL',
    experienceLevel: 'intermediate',
    movementPattern: 'hinge',
  },
  14: {
    id: 14,
    name: 'Kettlebell Clean Plus Front Squat',
    section: 'Full Body Power',
    equipment: ['kettlebell'],
    musclesWorked: ['full body'],
    coachingCues: 'Clean bell to rack position, from rack squat, full lower and upper body compound',
    progression: 'Double KB clean front squat or thruster',
    regression: 'KB deadlift plus goblet squat separate',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
  15: {
    id: 15,
    name: 'Kettlebell Farmers Carry',
    section: 'Loaded Carry',
    equipment: ['kettlebell'],
    musclesWorked: ['core', 'grip', 'traps'],
    coachingCues: 'Heavy KBs one in each hand, walk tall no lean, brace core, shoulders packed down, grip handles hard',
    progression: 'Single arm suitcase carry or overhead carry',
    regression: 'Light dumbbell carry',
    experienceLevel: 'intermediate',
    movementPattern: 'carry',
  },
  16: {
    id: 16,
    name: 'Banded Hip Thrust',
    section: 'Lower Body Hinge',
    equipment: ['bands', 'bench'],
    musclesWorked: ['glutes', 'hamstrings'],
    coachingCues: 'Band looped around hips, same mechanics as barbell hip thrust, drives against band at top for peak tension',
    progression: 'Add barbell through band or pulse at top 5 reps',
    regression: 'Bodyweight glute bridge with band above knees lying flat',
    experienceLevel: 'beginner',
    movementPattern: 'hinge',
  },
  17: {
    id: 17,
    name: 'Banded Lateral Walk',
    section: 'Lower Body Accessory',
    equipment: ['bands'],
    musclesWorked: ['glute med', 'hip abductors'],
    coachingCues: 'Band above knees or ankles, slight squat, step laterally keeping tension in band, do NOT let knees cave',
    progression: 'Monster walk or add DBs in hands',
    regression: 'Seated band abduction',
    experienceLevel: 'beginner',
    movementPattern: 'carry',
  },
  18: {
    id: 18,
    name: 'Banded Squat Mini Band Above Knees',
    section: 'Lower Body Strength',
    equipment: ['bands'],
    musclesWorked: ['quads', 'glutes'],
    coachingCues: 'Band above knees, goblet squat or bodyweight, push knees out into band',
    progression: 'Barbell squat with band for accommodating resistance',
    regression: 'Clamshell with band',
    experienceLevel: 'beginner',
    movementPattern: 'squat',
  },
  19: {
    id: 19,
    name: 'Banded Pull Through',
    section: 'Lower Body Hinge',
    equipment: ['bands'],
    musclesWorked: ['glutes', 'hamstrings'],
    coachingCues: 'Band anchored low behind, face away, hinge forward, drive hips forward to stand, pure hip extension',
    progression: 'KB swing',
    regression: 'Seated hip extension or lying banded glute bridge',
    experienceLevel: 'beginner',
    movementPattern: 'hinge',
  },
  20: {
    id: 20,
    name: 'Banded Good Morning',
    section: 'Lower Body Hinge',
    equipment: ['bands'],
    musclesWorked: ['hamstrings', 'glutes', 'erectors'],
    coachingCues: 'Band under feet looped over upper back, hip hinge soft knee bend, hamstring stretch at bottom, squeeze glutes to return',
    progression: 'Barbell good morning',
    regression: 'Lying hamstring curl with band',
    experienceLevel: 'beginner',
    movementPattern: 'hinge',
  },
  21: {
    id: 21,
    name: 'Medicine Ball Wall Squat Plus Slam',
    section: 'Full Body Power',
    equipment: ['medicineBall', 'box'],
    musclesWorked: ['full body'],
    coachingCues: 'Hold ball overhead, squat deep, as you stand accelerate upward and slam with full power',
    progression: 'Double med ball or weighted vest',
    regression: 'Bodyweight squat only',
    experienceLevel: 'beginner',
    movementPattern: 'power',
  },
  22: {
    id: 22,
    name: 'Medicine Ball Rotational Slam',
    section: 'Full Body Power',
    equipment: ['medicineBall'],
    musclesWorked: ['core', 'shoulders'],
    coachingCues: 'Stand perpendicular to wall, rotate load hip, drive ball into wall with full torso rotation, train both sides',
    progression: 'Step and slam',
    regression: 'Seated rotational throw against wall',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  23: {
    id: 23,
    name: 'Medicine Ball Deadball Over Shoulder',
    section: 'Full Body Power',
    equipment: ['sandbag'],
    musclesWorked: ['full body'],
    coachingCues: 'Pick heavy deadball from floor throw over shoulder alternating sides, pure power and athleticism',
    progression: 'Heavier deadball or add burpee before each rep',
    regression: 'KB deadlift to stand',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
  24: {
    id: 24,
    name: 'Medicine Ball Russian Twist',
    section: 'Core',
    equipment: ['medicineBall'],
    musclesWorked: ['obliques', 'core'],
    coachingCues: 'Seated feet off or on floor, hold ball at chest, rotate fully side to side from thoracic spine not just arms',
    progression: 'Lower legs flat add press at each end range',
    regression: 'Feet on floor bodyweight only',
    experienceLevel: 'beginner',
    movementPattern: 'core',
  },
  25: {
    id: 25,
    name: 'Medicine Ball Clean Plus Press',
    section: 'Full Body Power',
    equipment: ['medicineBall'],
    musclesWorked: ['full body'],
    coachingCues: 'Deadball from floor to chest then press overhead, full body power, brace core hard before press',
    progression: 'Dumbbell or barbell clean plus press',
    regression: 'KB clean from hang position',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  26: {
    id: 26,
    name: 'Barbell Bench Press',
    section: 'Upper Body Push',
    equipment: ['barbell', 'bench'],
    musclesWorked: ['chest', 'triceps', 'anterior deltoid'],
    coachingCues: 'Arch naturally, shoulder blades pinched and depressed, bar to lower chest, elbows at 45 degrees, full ROM',
    progression: 'Close grip bench or 2 second pause at chest',
    regression: 'Dumbbell floor press',
    experienceLevel: 'intermediate',
    movementPattern: 'push',
  },
  27: {
    id: 27,
    name: 'Barbell Overhead Press Standing',
    section: 'Upper Body Push',
    equipment: ['barbell'],
    musclesWorked: ['shoulders', 'triceps', 'core'],
    coachingCues: 'Grip just outside shoulder width, bar starts on upper chest, drive bar straight up, move head back then forward, lock out fully',
    progression: 'Push press or slow eccentric 4 seconds down',
    regression: 'Seated dumbbell shoulder press',
    experienceLevel: 'intermediate',
    movementPattern: 'push',
  },
  28: {
    id: 28,
    name: 'Barbell Incline Press',
    section: 'Upper Body Push',
    equipment: ['barbell', 'bench'],
    musclesWorked: ['upper chest', 'anterior deltoid', 'triceps'],
    coachingCues: 'Bench at 30 to 45 degrees, same principles as flat bench, higher angle more shoulder lower angle more chest',
    progression: 'Incline dumbbell press for greater ROM',
    regression: 'Incline push up',
    experienceLevel: 'intermediate',
    movementPattern: 'push',
  },
  29: {
    id: 29,
    name: 'Dumbbell Arnold Press',
    section: 'Upper Body Push',
    equipment: ['dumbbells'],
    musclesWorked: ['shoulders', 'triceps', 'rotator cuff'],
    coachingCues: 'Start palms facing you, rotate to pronated grip at top as you press, reverse on way down',
    progression: 'Single arm Arnold press or standing',
    regression: 'Seated dumbbell lateral raise',
    experienceLevel: 'beginner',
    movementPattern: 'push',
  },
  30: {
    id: 30,
    name: 'Dumbbell Chest Fly',
    section: 'Upper Body Push',
    equipment: ['dumbbells', 'bench'],
    musclesWorked: ['chest'],
    coachingCues: 'Slight bend in elbows maintain throughout, lower with control until deep stretch, squeeze chest hard as DBs come together',
    progression: 'Cable fly',
    regression: 'Band chest fly or push up with pause',
    experienceLevel: 'beginner',
    movementPattern: 'push',
  },
  31: {
    id: 31,
    name: 'Dumbbell Push Press',
    section: 'Upper Body Power',
    equipment: ['dumbbells'],
    musclesWorked: ['shoulders', 'triceps', 'legs'],
    coachingCues: 'DBs at shoulder height, dip slightly at knees, explosively drive hips up and press overhead in one movement',
    progression: 'Barbell push press or single arm',
    regression: 'Seated dumbbell press',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  32: {
    id: 32,
    name: 'Kettlebell Press Strict',
    section: 'Upper Body Push',
    equipment: ['kettlebell'],
    musclesWorked: ['shoulders', 'triceps'],
    coachingCues: 'Bell racked on forearm, elbow in, press straight up, arm fully locked at top, no hip drive',
    progression: 'Double KB press or barbell overhead press',
    regression: 'KB floor press',
    experienceLevel: 'intermediate',
    movementPattern: 'push',
  },
  33: {
    id: 33,
    name: 'Kettlebell Half Kneeling Press',
    section: 'Upper Body Push',
    equipment: ['kettlebell'],
    musclesWorked: ['shoulders', 'core'],
    coachingCues: 'Down on one knee opposite knee forward, press on kneeling side, forces pure shoulder pressing without any lean',
    progression: 'Add rotation away from pressing arm at lockout',
    regression: 'Band press from half kneeling',
    experienceLevel: 'intermediate',
    movementPattern: 'push',
  },
  34: {
    id: 34,
    name: 'Banded Push Up',
    section: 'Upper Body Push',
    equipment: ['bands'],
    musclesWorked: ['chest', 'triceps', 'shoulders'],
    coachingCues: 'Band across upper back hands gripping ends, push up band adds resistance at top',
    progression: 'Weighted push up vest or ring push up',
    regression: 'Incline push up hands on bench',
    experienceLevel: 'beginner',
    movementPattern: 'push',
  },
  35: {
    id: 35,
    name: 'Banded Overhead Tricep Extension',
    section: 'Upper Body Push',
    equipment: ['bands'],
    musclesWorked: ['triceps'],
    coachingCues: 'Band anchored behind and above, extend at elbow from 90 degrees to full lockout, keep upper arm fixed',
    progression: 'Close grip bench or barbell skull crusher',
    regression: 'KB overhead tricep extension',
    experienceLevel: 'beginner',
    movementPattern: 'push',
  },
  36: {
    id: 36,
    name: 'Medicine Ball Chest Pass Against Wall',
    section: 'Upper Body Power',
    equipment: ['medicineBall'],
    musclesWorked: ['chest', 'shoulders'],
    coachingCues: 'Stand 1 to 2 metres from wall, explosively press against wall, catch and immediately reload',
    progression: 'Overhead chest pass or plyometric push up',
    regression: 'Slow med ball push against wall',
    experienceLevel: 'beginner',
    movementPattern: 'push',
  },
  37: {
    id: 37,
    name: 'Barbell Bent Over Row',
    section: 'Upper Body Pull',
    equipment: ['barbell'],
    musclesWorked: ['lats', 'rhomboids', 'rear deltoid', 'biceps'],
    coachingCues: 'Hip hinge at 45 degrees, bar pulls to lower rib cage, drive elbows back and up, squeeze shoulder blades',
    progression: 'Pendlay row or Yates row',
    regression: 'Dumbbell row or banded row',
    experienceLevel: 'intermediate',
    movementPattern: 'pull',
  },
  38: {
    id: 38,
    name: 'Barbell Sumo High Pull',
    section: 'Upper Body Power',
    equipment: ['barbell'],
    musclesWorked: ['traps', 'shoulders', 'glutes'],
    coachingCues: 'Wide stance, explosive hip extension, pull bar to chin height leading with elbows, hip drive does the work',
    progression: 'Full power clean',
    regression: 'KB or DB upright row',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
  39: {
    id: 39,
    name: 'Dumbbell Single Arm Row',
    section: 'Upper Body Pull',
    equipment: ['dumbbells', 'bench'],
    musclesWorked: ['lats', 'rhomboids', 'biceps'],
    coachingCues: 'Brace on bench with opposite hand, pull DB to hip not shoulder, elbow stays tight, squeeze lat hard hold 1 second',
    progression: 'Renegade row',
    regression: 'Cable row or banded row seated',
    experienceLevel: 'beginner',
    movementPattern: 'pull',
  },
  40: {
    id: 40,
    name: 'Dumbbell Incline Y T W Raise',
    section: 'Upper Body Pull',
    equipment: ['dumbbells', 'bench'],
    musclesWorked: ['lower traps', 'rotator cuff'],
    coachingCues: 'Lie face down on incline bench, perform Y arms 45 degrees overhead, T arms out to sides, W elbows bent 90 degrees',
    progression: 'Add light load 1 to 2kg or 3 second hold',
    regression: 'Bodyweight prone cobra',
    experienceLevel: 'intermediate',
    movementPattern: 'pull',
  },
  41: {
    id: 41,
    name: 'Dumbbell Hammer Curl',
    section: 'Upper Body Pull',
    equipment: ['dumbbells'],
    musclesWorked: ['brachialis', 'brachioradialis', 'biceps'],
    coachingCues: 'Neutral grip throughout, curl without wrist rotation, keep upper arms fixed',
    progression: 'Cross body hammer curl or incline dumbbell curl',
    regression: 'Band hammer curl or cable curl neutral',
    experienceLevel: 'beginner',
    movementPattern: 'pull',
  },
  42: {
    id: 42,
    name: 'Kettlebell Renegade Row',
    section: 'Upper Body Pull',
    equipment: ['kettlebell'],
    musclesWorked: ['lats', 'core', 'anti-rotation'],
    coachingCues: 'Plank on two KBs handles parallel, row one KB to hip, replace, row other, do not rotate hips, feet wide',
    progression: 'Add push up between each row or narrow feet',
    regression: 'Plank with alternating shoulder tap',
    experienceLevel: 'intermediate',
    movementPattern: 'pull',
  },
  43: {
    id: 43,
    name: 'Kettlebell Snatch',
    section: 'Full Body Power',
    equipment: ['kettlebell'],
    musclesWorked: ['full body'],
    coachingCues: 'From hike explosive hip snap, bell goes overhead in one fluid motion, no banging on wrist at top, punch through',
    progression: 'Double KB snatch or barbell hang snatch',
    regression: 'KB swing to eye level',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
  44: {
    id: 44,
    name: 'Kettlebell Reverse Row',
    section: 'Upper Body Pull',
    equipment: ['kettlebell', 'bands'],
    musclesWorked: ['lats', 'biceps', 'rear deltoid'],
    coachingCues: 'Anchor two KBs loop band or bar across, bodyweight row, body straight, pull chest to handles',
    progression: 'Add feet elevation or weighted vest',
    regression: 'Incline row body angled more upright',
    experienceLevel: 'intermediate',
    movementPattern: 'pull',
  },
  45: {
    id: 45,
    name: 'Banded Face Pull',
    section: 'Upper Body Pull',
    equipment: ['bands'],
    musclesWorked: ['posterior deltoid', 'rotator cuff', 'rhomboids'],
    coachingCues: 'Band anchored at face height, pull to sides of face, elbows high and back, hands end up at ear level, external rotation',
    progression: 'Cable face pull or 2 second hold at end range',
    regression: 'Band pull apart',
    experienceLevel: 'beginner',
    movementPattern: 'pull',
  },
  46: {
    id: 46,
    name: 'Banded Lat Pulldown',
    section: 'Upper Body Pull',
    equipment: ['bands'],
    musclesWorked: ['lats', 'biceps'],
    coachingCues: 'Band anchored overhead, kneel or sit, pull elbows down to hips not just hands, think elbows in back pockets',
    progression: 'Cable lat pulldown or assisted pull up',
    regression: 'Straight arm banded pulldown',
    experienceLevel: 'beginner',
    movementPattern: 'pull',
  },
  47: {
    id: 47,
    name: 'Barbell Rollout',
    section: 'Core',
    equipment: ['barbell'],
    musclesWorked: ['core', 'anti-extension'],
    coachingCues: 'Barbell with small plates, kneel, roll forward from hips, body rigid like plank, go until back almost hyperextends then pull back',
    progression: 'Standing barbell rollout',
    regression: 'Ab wheel from knees limited range or plank',
    experienceLevel: 'advanced',
    movementPattern: 'core',
  },
  48: {
    id: 48,
    name: 'Pallof Press',
    section: 'Core',
    equipment: ['bands', 'cable'],
    musclesWorked: ['core', 'anti-rotation'],
    coachingCues: 'Band anchored to side, stand perpendicular, press straight out in front, resist rotation, hold 2 seconds, return',
    progression: 'Half kneeling or kneeling Pallof press',
    regression: 'Seated Pallof press or supine dead bug',
    experienceLevel: 'intermediate',
    movementPattern: 'core',
  },
  49: {
    id: 49,
    name: 'KB Turkish Get Up',
    section: 'Core',
    equipment: ['kettlebell'],
    musclesWorked: ['full body', 'stability'],
    coachingCues: 'From lying with KB pressed up, arm vertical throughout every phase, move through lying half-kneeling standing and back down in controlled sequence',
    progression: 'Heavier KB or pause at each position 2 to 3 seconds',
    regression: 'Fist get up no weight',
    experienceLevel: 'advanced',
    movementPattern: 'core',
  },
  50: {
    id: 50,
    name: 'Medicine Ball Slam Power Core',
    section: 'Core',
    equipment: ['medicineBall'],
    musclesWorked: ['core', 'shoulders'],
    coachingCues: 'Overhead full extension go up on toes, slam with maximum force into ground',
    progression: 'Add burpee after each slam or bounce slam',
    regression: 'Dowel or light weight overhead reach and controlled lower',
    experienceLevel: 'beginner',
    movementPattern: 'core',
  },
  51: {
    id: 51,
    name: 'Dead Bug',
    section: 'Core',
    equipment: ['bodyweight'],
    musclesWorked: ['core', 'anti-extension'],
    coachingCues: 'Lying on back, arms to ceiling, knees at 90 degrees, lower opposite arm and leg simultaneously pressing lower back HARD into floor, return, alternate',
    progression: 'Add dumbbell in each hand or band across thighs',
    regression: 'Arm only or leg only variation',
    experienceLevel: 'beginner',
    movementPattern: 'core',
  },
  52: {
    id: 52,
    name: 'Suitcase Carry',
    section: 'Loaded Carry',
    equipment: ['dumbbells', 'kettlebell'],
    musclesWorked: ['core', 'anti-lateral-flexion', 'grip'],
    coachingCues: 'One heavy weight in one hand, walk 20 to 30 metres, goal is zero lateral lean',
    progression: 'Bottoms up suitcase carry',
    regression: 'Band resisted walk',
    experienceLevel: 'intermediate',
    movementPattern: 'carry',
  },
  53: {
    id: 53,
    name: 'Box Squat',
    section: 'Lower Body Strength',
    equipment: ['box', 'bench'],
    musclesWorked: ['quads', 'glutes'],
    coachingCues: 'Sit back onto box pause 1 to 2 seconds, drive through heels to stand, box teaches depth and removes fear of squatting below parallel',
    progression: 'Remove box and squat same depth freely',
    regression: 'Squat to higher box or chair',
    experienceLevel: 'beginner',
    movementPattern: 'squat',
  },
  54: {
    id: 54,
    name: 'Bodyweight Glute Bridge',
    section: 'Lower Body Hinge',
    equipment: ['bodyweight'],
    musclesWorked: ['glutes', 'hamstrings'],
    coachingCues: 'Lying on back feet flat hip-width, drive hips up to full extension, squeeze hard at top 2 seconds, lower slowly',
    progression: 'Single leg glute bridge then elevated single leg',
    regression: 'Supine hip extension small lift',
    experienceLevel: 'beginner',
    movementPattern: 'hinge',
  },
  55: {
    id: 55,
    name: 'Wall Sit',
    section: 'Lower Body Strength',
    equipment: ['bodyweight'],
    musclesWorked: ['quads', 'hip flexors'],
    coachingCues: 'Back flat against wall, thighs parallel to floor, hold, builds quad endurance and teaches isometric squat position',
    progression: 'Add dumbbell or plate on thighs or single leg wall sit',
    regression: 'Higher wall sit angle above 90 degrees',
    experienceLevel: 'beginner',
    movementPattern: 'squat',
  },
  56: {
    id: 56,
    name: 'Seated Leg Extension Band',
    section: 'Lower Body Accessory',
    equipment: ['bands', 'bench'],
    musclesWorked: ['quads'],
    coachingCues: 'Band looped around ankles seated on bench, extend one leg to full lockout against band, control eccentric 3 seconds',
    progression: 'Add 2 second hold at full extension or increase band',
    regression: 'Straight leg raise from lying',
    experienceLevel: 'beginner',
    movementPattern: 'squat',
  },
  57: {
    id: 57,
    name: 'Standing Hip Abduction Band',
    section: 'Lower Body Accessory',
    equipment: ['bands'],
    musclesWorked: ['glute med'],
    coachingCues: 'Band above ankles, stand on one foot, lift working leg out to side against band, keep torso upright do not lean',
    progression: 'Cable machine or ankle weight',
    regression: 'Lying side-lying hip abduction',
    experienceLevel: 'beginner',
    movementPattern: 'carry',
  },
  58: {
    id: 58,
    name: 'Incline Push Up',
    section: 'Upper Body Push',
    equipment: ['bodyweight', 'bench'],
    musclesWorked: ['chest', 'triceps', 'shoulders'],
    coachingCues: 'Hands on bench or box, body in straight plank, lower chest to surface press back up',
    progression: 'Decline push up or add resistance band',
    regression: 'Wall push up',
    experienceLevel: 'beginner',
    movementPattern: 'push',
  },
  59: {
    id: 59,
    name: 'Banded Bicep Curl',
    section: 'Upper Body Pull',
    equipment: ['bands'],
    musclesWorked: ['biceps'],
    coachingCues: 'Stand on band, curl up with elbows pinned to sides, full range all the way up controlled all the way down, squeeze at top',
    progression: 'Dumbbell curl then barbell curl',
    regression: 'Seated dumbbell curl',
    experienceLevel: 'beginner',
    movementPattern: 'pull',
  },
  60: {
    id: 60,
    name: 'Banded Tricep Pushdown',
    section: 'Upper Body Push',
    equipment: ['bands'],
    musclesWorked: ['triceps'],
    coachingCues: 'Band anchored overhead, elbows at sides lock them there, push down to full lockout, do NOT let elbows drift forward, squeeze tricep hard',
    progression: 'Cable rope pushdown or overhead tricep extension',
    regression: 'Tricep dips off bench',
    experienceLevel: 'beginner',
    movementPattern: 'push',
  },
  61: {
    id: 61,
    name: 'Dumbbell Lateral Raise',
    section: 'Upper Body Accessory',
    equipment: ['dumbbells'],
    musclesWorked: ['medial deltoid'],
    coachingCues: 'Slight bend in elbows, raise arms to shoulder height no higher, lead with elbows not hands, slow eccentric 3 seconds',
    progression: 'Cable lateral raise or lean-away cable raise',
    regression: 'Band lateral raise or seated dumbbell lateral raise',
    experienceLevel: 'beginner',
    movementPattern: 'push',
  },
  62: {
    id: 62,
    name: 'Dumbbell Front Raise',
    section: 'Upper Body Accessory',
    equipment: ['dumbbells'],
    musclesWorked: ['anterior deltoid'],
    coachingCues: 'Arms straight or slight elbow bend, raise to eye level no higher, alternate or both together, slow eccentric, do not swing torso',
    progression: 'Plate front raise or cable front raise',
    regression: 'Seated front raise',
    experienceLevel: 'beginner',
    movementPattern: 'push',
  },
  63: {
    id: 63,
    name: 'Seated Cable Row Close Grip',
    section: 'Upper Body Pull',
    equipment: ['cable'],
    musclesWorked: ['lats', 'rhomboids', 'biceps'],
    coachingCues: 'Sit tall slight lean back, pull to lower rib, squeeze shoulder blades hard at end, controlled return feel the stretch',
    progression: 'Wide grip cable row or single arm cable row',
    regression: 'Banded seated row',
    experienceLevel: 'intermediate',
    movementPattern: 'pull',
  },
  64: {
    id: 64,
    name: 'Chest Supported Dumbbell Row',
    section: 'Upper Body Pull',
    equipment: ['dumbbells', 'bench'],
    musclesWorked: ['lats', 'rhomboids', 'rear deltoid'],
    coachingCues: 'Lie face down on 45 degree incline bench, row both DBs simultaneously to hips, removes ALL lower back involvement',
    progression: 'Add 1 second pause at top or use barbell',
    regression: 'Seated cable row',
    experienceLevel: 'intermediate',
    movementPattern: 'pull',
  },
  65: {
    id: 65,
    name: 'Dumbbell Shrug',
    section: 'Upper Body Accessory',
    equipment: ['dumbbells'],
    musclesWorked: ['upper traps'],
    coachingCues: 'DBs at sides, shrug straight up toward ears no rolling, hold 1 to 2 seconds at top, slow eccentric',
    progression: 'Barbell shrug or farmers carry as loaded isometric',
    regression: 'Band shrug or bodyweight neck isometrics',
    experienceLevel: 'beginner',
    movementPattern: 'pull',
  },
  66: {
    id: 66,
    name: 'Plank Hold',
    section: 'Core',
    equipment: ['bodyweight'],
    musclesWorked: ['core', 'anti-extension'],
    coachingCues: 'Forearms or hands on floor, body in straight line hips not sagging not raised, squeeze everything glutes quads core, breathe',
    progression: 'Add shoulder taps leg lifts or weight plate on back',
    regression: 'Plank from knees',
    experienceLevel: 'beginner',
    movementPattern: 'core',
  },
  67: {
    id: 67,
    name: 'Hollow Body Hold',
    section: 'Core',
    equipment: ['bodyweight'],
    musclesWorked: ['core', 'anti-extension'],
    coachingCues: 'Lying on back, arms overhead, legs straight slightly raised, lower back pressed firmly into floor, hold',
    progression: 'Hollow body rock or add medicine ball',
    regression: 'Tuck hold knees pulled to chest',
    experienceLevel: 'beginner',
    movementPattern: 'core',
  },
  68: {
    id: 68,
    name: 'Bird Dog',
    section: 'Core',
    equipment: ['bodyweight'],
    musclesWorked: ['core', 'stability'],
    coachingCues: 'On hands and knees, extend opposite arm and leg simultaneously, hold 2 seconds, return with control, zero movement of spine',
    progression: 'Add wrist weight or ankle weight or perform on bench',
    regression: 'Arm only or leg only extension',
    experienceLevel: 'beginner',
    movementPattern: 'core',
  },
  69: {
    id: 69,
    name: 'Side Plank',
    section: 'Core',
    equipment: ['bodyweight'],
    musclesWorked: ['core', 'anti-lateral-flexion', 'obliques'],
    coachingCues: 'Side forearm on floor, stack feet or stagger, body in straight diagonal line, do not let hip sag, breathe',
    progression: 'Side plank with hip abduction or thread the needle',
    regression: 'Side plank from knees',
    experienceLevel: 'beginner',
    movementPattern: 'core',
  },
  70: {
    id: 70,
    name: 'Lying Leg Raise',
    section: 'Core',
    equipment: ['bodyweight'],
    musclesWorked: ['core', 'anti-extension', 'hip flexors'],
    coachingCues: 'Lying flat, hands under lower back for support, raise straight legs to 90 degrees, lower slowly stop before lower back arches off floor',
    progression: 'Hanging leg raise or decline bench leg raise',
    regression: 'Bent knee leg raise',
    experienceLevel: 'beginner',
    movementPattern: 'core',
  },
  71: {
    id: 71,
    name: 'Barbell Power Clean',
    section: 'Full Body Power',
    equipment: ['barbell'],
    musclesWorked: ['full body'],
    coachingCues: 'Start like a deadlift, explosively drive hips, bar accelerates past hips, shrug pull under catch in front rack, full-body power movement',
    progression: 'Barbell full clean plus front squat or clean and jerk',
    regression: 'Hang power clean or dumbbell clean',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
  72: {
    id: 72,
    name: 'Barbell Thruster',
    section: 'Full Body Power',
    equipment: ['barbell'],
    musclesWorked: ['full body'],
    coachingCues: 'Front rack, squat to depth, as you drive up use leg power to initiate overhead press, one fluid movement, legs power the press',
    progression: 'Dumbbell thruster or kettlebell thruster',
    regression: 'Goblet squat plus press as two separate movements',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
  73: {
    id: 73,
    name: 'Barbell Hang Power Snatch',
    section: 'Full Body Power',
    equipment: ['barbell'],
    musclesWorked: ['full body'],
    coachingCues: 'Bar at hip crease, aggressive hip snap shrug and punch overhead in one motion, catch with locked arms',
    progression: 'Full squat snatch',
    regression: 'DB or KB snatch single arm',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
  74: {
    id: 74,
    name: 'Barbell Landmine Press',
    section: 'Upper Body Push',
    equipment: ['barbell'],
    musclesWorked: ['shoulders', 'chest', 'core'],
    coachingCues: 'One end of bar in corner or landmine anchor, press from shoulder height at 45 degree angle, joint-friendly',
    progression: 'Landmine squat to press or single arm landmine press',
    regression: 'Seated landmine press or banded press at same angle',
    experienceLevel: 'intermediate',
    movementPattern: 'push',
  },
  75: {
    id: 75,
    name: 'Barbell Zercher Squat',
    section: 'Lower Body Strength',
    equipment: ['barbell'],
    musclesWorked: ['quads', 'core', 'biceps', 'upper back'],
    coachingCues: 'Bar in crooks of elbows held against chest, squat deep, brutally hard on biceps core and upper back, forces upright torso',
    progression: 'Barbell front squat or safety bar squat',
    regression: 'Goblet squat',
    experienceLevel: 'advanced',
    movementPattern: 'squat',
  },
  76: {
    id: 76,
    name: 'Barbell Good Morning',
    section: 'Lower Body Hinge',
    equipment: ['barbell'],
    musclesWorked: ['hamstrings', 'glutes', 'erectors'],
    coachingCues: 'Bar on upper back like squat, hinge at hips soft knee bend, lower until back nearly parallel, squeeze glutes to stand',
    progression: 'Deficit good morning or banded good morning',
    regression: 'Banded good morning or Romanian deadlift',
    experienceLevel: 'advanced',
    movementPattern: 'hinge',
  },
  77: {
    id: 77,
    name: 'Dumbbell Devil Press',
    section: 'Full Body Power',
    equipment: ['dumbbells'],
    musclesWorked: ['full body'],
    coachingCues: 'Start standing, lower DBs to floor, jump out to push up, push up, jump feet in, clean and press DBs overhead in one motion, conditioning staple',
    progression: 'Add burpee before clean or increase DB weight',
    regression: 'DB clean plus press only remove burpee',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
  78: {
    id: 78,
    name: 'Dumbbell Snatch',
    section: 'Full Body Power',
    equipment: ['dumbbells'],
    musclesWorked: ['full body'],
    coachingCues: 'Hinge and hike DB between legs, explosive hip drive, pull DB overhead with straight arm, catch locked out, one arm at a time',
    progression: 'Increase DB weight or alternating arm snatch without putting down',
    regression: 'DB clean to shoulder just the pull phase',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  79: {
    id: 79,
    name: 'Dumbbell Man Maker',
    section: 'Full Body Power',
    equipment: ['dumbbells'],
    musclesWorked: ['full body'],
    coachingCues: 'Push up then renegade row left then renegade row right then jump feet in then power clean then overhead press, that is one rep',
    progression: 'Add squat after press or increase DB weight',
    regression: 'Dumbbell push up plus row only',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
  80: {
    id: 80,
    name: 'Dumbbell Clean Plus Squat Plus Press Thruster',
    section: 'Full Body Power',
    equipment: ['dumbbells'],
    musclesWorked: ['full body'],
    coachingCues: 'Clean DBs to shoulders, front squat to depth, drive up, use momentum to press overhead, one fluid chain',
    progression: 'Barbell thruster or KB double thruster',
    regression: 'DB squat plus press as two separate movements',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  81: {
    id: 81,
    name: 'Kettlebell Flow Deadlift Clean Press Squat',
    section: 'Full Body Power',
    equipment: ['kettlebell'],
    musclesWorked: ['full body'],
    coachingCues: 'One KB, deadlift it, clean to rack, press overhead, lower to rack, squat, return to floor, one rep',
    progression: 'Double KB flow or increase weight',
    regression: 'Perform each movement separately with rest between',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
  82: {
    id: 82,
    name: 'Kettlebell Windmill',
    section: 'Core',
    equipment: ['kettlebell'],
    musclesWorked: ['shoulder stability', 'core', 'obliques'],
    coachingCues: 'KB pressed overhead, eyes on KB at all times, hinge laterally push hip out on KB side, reach free hand toward floor',
    progression: 'Increase KB weight or double KB windmill',
    regression: 'Bodyweight windmill or light dumbbell overhead',
    experienceLevel: 'advanced',
    movementPattern: 'core',
  },
  83: {
    id: 83,
    name: 'Kettlebell Clean Plus Jerk',
    section: 'Full Body Power',
    equipment: ['kettlebell'],
    musclesWorked: ['full body'],
    coachingCues: 'Clean to rack, dip at knees slight, explosively drive up leg power initiates jerk, punch overhead split or power stance',
    progression: 'Double KB clean and jerk or barbell clean and jerk',
    regression: 'KB press from rack remove jerk',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
  84: {
    id: 84,
    name: 'Kettlebell Pistol Squat Assist',
    section: 'Lower Body Unilateral',
    equipment: ['kettlebell'],
    musclesWorked: ['quads', 'glutes', 'core', 'balance'],
    coachingCues: 'Hold KB at chest for counterbalance, stand on one leg, extend other leg forward, squat all the way down on one leg',
    progression: 'Full unassisted pistol squat or weighted',
    regression: 'Box pistol squat lower onto box',
    experienceLevel: 'advanced',
    movementPattern: 'squat',
  },
  85: {
    id: 85,
    name: 'KB Lunge to Overhead Press Alternating',
    section: 'Full Body Power',
    equipment: ['kettlebell'],
    musclesWorked: ['full body'],
    coachingCues: 'Hold KB in one hand at shoulder racked, step into lunge, as you drive back up press KB overhead, lower as you step into next lunge other side',
    progression: 'Double KB version or barbell overhead walking lunge',
    regression: 'Lunge only remove press',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  86: {
    id: 86,
    name: 'Med Ball Burpee to Slam',
    section: 'Full Body Power',
    equipment: ['medicineBall'],
    musclesWorked: ['full body'],
    coachingCues: 'Holding med ball perform burpee, land stand raise ball overhead slam hard pick up immediately continuous, conditioning benchmark',
    progression: 'Wear weight vest or increase ball weight',
    regression: 'Med ball slam only remove burpee',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  87: {
    id: 87,
    name: 'Med Ball Squat Plus Chest Pass',
    section: 'Full Body Power',
    equipment: ['medicineBall'],
    musclesWorked: ['full body'],
    coachingCues: 'Hold ball at chest, squat to depth, as you drive up use leg power to chest pass ball explosively',
    progression: 'Add jump at top before pass',
    regression: 'Squat and separate pass two movements with pause',
    experienceLevel: 'beginner',
    movementPattern: 'power',
  },
  88: {
    id: 88,
    name: 'Med Ball Turkish Get Up',
    section: 'Core',
    equipment: ['medicineBall'],
    musclesWorked: ['full body', 'stability'],
    coachingCues: 'Same movement as KB Turkish Get Up but with medicine ball, round surface makes it harder to control',
    progression: 'KB Turkish Get Up with heavier bell',
    regression: 'Fist TGU no weight',
    experienceLevel: 'advanced',
    movementPattern: 'core',
  },
  89: {
    id: 89,
    name: 'Med Ball Lateral Bound Plus Slam',
    section: 'Full Body Power',
    equipment: ['medicineBall'],
    musclesWorked: ['full body'],
    coachingCues: 'Hold light med ball, lateral bound to one side stick landing, immediately slam ball into ground, pick up and bound back',
    progression: 'Increase bound distance or heavier ball',
    regression: 'Lateral step plus slam remove bound',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  90: {
    id: 90,
    name: 'Med Ball Bear Crawl Push',
    section: 'Metabolic Conditioning',
    equipment: ['medicineBall'],
    musclesWorked: ['shoulders', 'core', 'hip flexors'],
    coachingCues: 'All fours in bear crawl, med ball under one hand, crawl forward pushing ball with each step then backward',
    progression: 'Add push up at each ball transfer',
    regression: 'Bear crawl without ball',
    experienceLevel: 'intermediate',
    movementPattern: 'conditioning',
  },
  91: {
    id: 91,
    name: 'Jump Squat',
    section: 'Lower Body Power',
    equipment: ['bodyweight'],
    musclesWorked: ['quads', 'glutes'],
    coachingCues: 'Squat to quarter depth, explode upward fully extend hips knees ankles, land softly through toes midfoot heel, reset',
    progression: 'Barbell jump squat 20 to 30 percent 1RM or depth jump',
    regression: 'Countermovement jump bodyweight focus on landing',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  92: {
    id: 92,
    name: 'Broad Jump',
    section: 'Lower Body Power',
    equipment: ['bodyweight'],
    musclesWorked: ['quads', 'glutes', 'hamstrings'],
    coachingCues: 'Athletic stance swing arms back dip at hips explode forward as far as possible land with soft knees',
    progression: 'Weighted vest broad jump or add drop to push up on landing',
    regression: 'Step jump forward reduce power and impact',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  93: {
    id: 93,
    name: 'Box Jump',
    section: 'Lower Body Power',
    equipment: ['box'],
    musclesWorked: ['quads', 'glutes'],
    coachingCues: 'Stand in front of box, athletic dip, explode up drive knees to chest, land softly on top, step down never jump down from height',
    progression: 'Depth jump or weighted box jump',
    regression: 'Step up onto box remove jump',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  94: {
    id: 94,
    name: 'Sprint Intervals 10 to 40m',
    section: 'Metabolic Conditioning',
    equipment: ['bodyweight'],
    musclesWorked: ['full body'],
    coachingCues: 'Set up markers, accelerate from standing or 3-point start, drive knees pump arms stay on balls of feet, full recovery between reps',
    progression: 'Resisted sprints sled or parachute or increase to 100m',
    regression: '5m acceleration drill only',
    experienceLevel: 'advanced',
    movementPattern: 'conditioning',
  },
  95: {
    id: 95,
    name: 'Sled Push',
    section: 'Metabolic Conditioning',
    equipment: ['sled'],
    musclesWorked: ['quads', 'glutes', 'core'],
    coachingCues: 'Low body position nearly parallel to floor, drive through balls of feet, short powerful steps, arms straight or bent',
    progression: 'Increase load or combine sled push plus sled pull',
    regression: 'Low resistance sled drag or prowler push minimal plates',
    experienceLevel: 'advanced',
    movementPattern: 'conditioning',
  },
  96: {
    id: 96,
    name: 'Sled Pull Rope or Strap',
    section: 'Metabolic Conditioning',
    equipment: ['sled'],
    musclesWorked: ['posterior chain', 'grip'],
    coachingCues: 'Facing sled with rope or strap, pull hand over hand or walk backward pulling, grip is limiting factor',
    progression: 'Increase load or combine with sled push on return',
    regression: 'Seated cable row same pattern no sled',
    experienceLevel: 'advanced',
    movementPattern: 'conditioning',
  },
  97: {
    id: 97,
    name: 'Wall Ball',
    section: 'Full Body Power',
    equipment: ['medicineBall', 'box'],
    musclesWorked: ['full body'],
    coachingCues: 'Hold ball at chest, squat deep, drive up throw ball to target on wall typically 3 to 4.5m high, catch go straight into next squat, conditioning event',
    progression: 'Increase target height or ball weight',
    regression: 'Med ball squat plus chest pass at low height',
    experienceLevel: 'intermediate',
    movementPattern: 'power',
  },
  98: {
    id: 98,
    name: 'Sandbag Carry Shoulder or Bear Hug',
    section: 'Loaded Carry',
    equipment: ['sandbag'],
    musclesWorked: ['core', 'grip', 'shoulders'],
    coachingCues: 'Shoulder carry bag on one shoulder walk with control, bear hug carry grip around middle walk with it pressed to chest',
    progression: 'Increase bag weight or distance',
    regression: 'Light DB farmers carry establish carry pattern first',
    experienceLevel: 'intermediate',
    movementPattern: 'carry',
  },
  99: {
    id: 99,
    name: 'Assault Bike All Out Intervals',
    section: 'Metabolic Conditioning',
    equipment: ['bodyweight'],
    musclesWorked: ['full body', 'cardiovascular'],
    coachingCues: 'Full extension on push full pull on return, use legs and arms equally, 10 sec all out 50 sec recovery or 20/40 or 30/30',
    progression: 'Increase all out interval duration or reduce rest',
    regression: 'Moderate steady state pace RPE 6 for 10 to 15 minutes',
    experienceLevel: 'intermediate',
    movementPattern: 'conditioning',
  },
  100: {
    id: 100,
    name: 'Ski Erg',
    section: 'Metabolic Conditioning',
    equipment: ['bodyweight'],
    musclesWorked: ['lats', 'core', 'cardiovascular'],
    coachingCues: 'Reach high pull down explosively past hips with locked elbows, use lat core and hip flexion, arms straight throughout pull phase',
    progression: 'Increase pace per 500m or ski erg intervals 250m sprint 30 sec rest times 8',
    regression: 'Standing cable pulldown',
    experienceLevel: 'intermediate',
    movementPattern: 'conditioning',
  },
  101: {
    id: 101,
    name: 'Rowing Machine',
    section: 'Metabolic Conditioning',
    equipment: ['bodyweight'],
    musclesWorked: ['full body', 'cardiovascular'],
    coachingCues: 'Legs then back then arms on pull, arms then back then legs on return, drive through heels keep chain level, damper at 3 to 5',
    progression: 'Increase pace per 500m or 10 max strokes times 10 rounds',
    regression: 'Steady 20 strokes per minute low resistance',
    experienceLevel: 'intermediate',
    movementPattern: 'conditioning',
  },
  102: {
    id: 102,
    name: 'Burpee to Pull Up',
    section: 'Full Body Power',
    equipment: ['pullUpBar'],
    musclesWorked: ['full body'],
    coachingCues: 'Burpee under a bar, jump up at top of burpee go straight into pull up, one fluid movement',
    progression: 'Strict muscle up or weighted pull up burpee',
    regression: 'Burpee plus jumping pull up',
    experienceLevel: 'advanced',
    movementPattern: 'power',
  },
}

export const SUPERSET_LIBRARY = {
  SS1: {
    id: 'SS1',
    name: 'Barbell Bench Press plus Barbell Bent Over Row',
    type: 'antagonist',
    exercise1: 'Barbell Bench Press',
    exercise2: 'Barbell Bent Over Row',
    coachNote: 'The bench fatigues chest and anterior deltoid, row works opposing lats rhomboids rear delts, each muscle fully recovers while the other works, can lift more total weight per session',
    bestFor: ['muscleBuilding', 'athletic'],
  },
  SS2: {
    id: 'SS2',
    name: 'Barbell Incline Press plus Chest Supported Dumbbell Row',
    type: 'antagonist',
    exercise1: 'Barbell Incline Press',
    exercise2: 'Chest Supported Dumbbell Row',
    coachNote: 'Incline pressing paired with chest-supported rowing keeps torso angle consistent and balances shoulder stress.',
    bestFor: ['muscleBuilding'],
  },
  SS3: {
    id: 'SS3',
    name: 'Dumbbell Bench Press plus Dumbbell Single Arm Row',
    type: 'antagonist',
    exercise1: 'Dumbbell Bench Press',
    exercise2: 'Dumbbell Single Arm Row',
    coachNote: 'Horizontal push and pull with dumbbells; alternate arms on rows to keep density high.',
    bestFor: ['muscleBuilding', 'strength'],
  },
  SS4: {
    id: 'SS4',
    name: 'Barbell Overhead Press plus Weighted Pull-Up',
    type: 'antagonist',
    exercise1: 'Barbell Overhead Press Standing',
    exercise2: 'Weighted Pull-Up',
    coachNote: 'Lats are direct antagonist of overhead press; resting one while working the other is mechanically perfect. Use additional load on pull-ups when prescribed, or band-assisted pull-up progressing to bodyweight and weighted.',
    bestFor: ['muscleBuilding', 'strength'],
  },
  SS5: {
    id: 'SS5',
    name: 'Dumbbell Arnold Press plus Banded Lat Pulldown',
    type: 'antagonist',
    exercise1: 'Dumbbell Arnold Press',
    exercise2: 'Banded Lat Pulldown',
    coachNote: 'Vertical-ish shoulder work with lat emphasis; great when a strict pull-up is not yet available.',
    bestFor: ['muscleBuilding'],
  },
  SS6: {
    id: 'SS6',
    name: 'Dumbbell Push Press plus Kettlebell Reverse Row',
    type: 'antagonist',
    exercise1: 'Dumbbell Push Press',
    exercise2: 'Kettlebell Reverse Row',
    coachNote: 'Explosive push with horizontal pull; maintains athletic rhythm.',
    bestFor: ['athletic', 'muscleBuilding'],
  },
  SS7: {
    id: 'SS7',
    name: 'Barbell Back Squat plus Lying Hamstring Curl',
    type: 'antagonist',
    exercise1: 'Barbell Back Squat',
    exercise2: 'Lying Hamstring Curl',
    coachNote: 'Quads recover during curl; hamstrings are not maximally fatigued by the squat, optimal loading for both. Use machine lying leg curl when available.',
    bestFor: ['muscleBuilding', 'athletic'],
  },
  SS8: {
    id: 'SS8',
    name: 'Barbell Front Squat plus Seated Leg Extension Band',
    type: 'antagonist',
    exercise1: 'Barbell Front Squat',
    exercise2: 'Seated Leg Extension Band',
    coachNote: 'Knee-extension quad work after a demanding squat pattern; keep extension controlled for tendon health.',
    bestFor: ['muscleBuilding'],
  },
  SS9: {
    id: 'SS9',
    name: 'Dumbbell Goblet Squat plus Banded Good Morning',
    type: 'antagonist',
    exercise1: 'Dumbbell Goblet Squat',
    exercise2: 'Banded Good Morning',
    coachNote: 'Knee-dominant squat alternated with hip-dominant hinge using complementary equipment.',
    bestFor: ['fatLoss', 'muscleBuilding'],
  },
  SS10: {
    id: 'SS10',
    name: 'Kettlebell Press Strict plus Banded Face Pull',
    type: 'antagonist',
    exercise1: 'Kettlebell Press Strict',
    exercise2: 'Banded Face Pull',
    coachNote: 'Vertical press with rear-delt and cuff emphasis; balances pressing volume.',
    bestFor: ['muscleBuilding', 'strength'],
  },
  SS11: {
    id: 'SS11',
    name: 'Medicine Ball Chest Pass Against Wall plus Banded Lat Pulldown',
    type: 'antagonist',
    exercise1: 'Medicine Ball Chest Pass Against Wall',
    exercise2: 'Banded Lat Pulldown',
    coachNote: 'Powerful horizontal push expression with lat-driven pull; great for athletic density.',
    bestFor: ['athletic', 'muscleBuilding'],
  },
  SS12: {
    id: 'SS12',
    name: 'Dumbbell Front Raise plus Banded Face Pull',
    type: 'antagonist',
    exercise1: 'Dumbbell Front Raise',
    exercise2: 'Banded Face Pull',
    coachNote: 'Anterior delt work with external-rotation face pull for shoulder balance.',
    bestFor: ['muscleBuilding'],
  },
  SS13: {
    id: 'SS13',
    name: 'Dumbbell Chest Fly plus Barbell Bench Press',
    type: 'agonist',
    exercise1: 'Dumbbell Chest Fly',
    exercise2: 'Barbell Bench Press',
    coachNote: 'Pre-fatigue chest with fly then compound bench; advanced trainees only.',
    bestFor: ['muscleBuilding'],
  },
  SS14: {
    id: 'SS14',
    name: 'Dumbbell Lateral Raise plus Dumbbell Arnold Press',
    type: 'agonist',
    exercise1: 'Dumbbell Lateral Raise',
    exercise2: 'Dumbbell Arnold Press',
    coachNote: 'Medial delt isolation before compound shoulder press.',
    bestFor: ['muscleBuilding'],
  },
  SS15: {
    id: 'SS15',
    name: 'Seated Leg Extension Band plus Barbell Back Squat',
    type: 'agonist',
    exercise1: 'Seated Leg Extension Band',
    exercise2: 'Barbell Back Squat',
    coachNote: 'Quad pre-exhaust before squat; use lighter squat loads and perfect technique.',
    bestFor: ['muscleBuilding'],
  },
  SS16: {
    id: 'SS16',
    name: 'Banded Tricep Pushdown plus Barbell Bench Press',
    type: 'agonist',
    exercise1: 'Banded Tricep Pushdown',
    exercise2: 'Barbell Bench Press',
    coachNote: 'Triceps pre-fatigue for bench emphasis; spotter or conservative loads recommended.',
    bestFor: ['muscleBuilding'],
  },
  SS17: {
    id: 'SS17',
    name: 'Banded Bicep Curl plus Barbell Bent Over Row',
    type: 'agonist',
    exercise1: 'Banded Bicep Curl',
    exercise2: 'Barbell Bent Over Row',
    coachNote: 'Arm flexors prefatigued before heavy rowing.',
    bestFor: ['muscleBuilding'],
  },
  SS18: {
    id: 'SS18',
    name: 'Banded Hip Thrust plus Barbell Romanian Deadlift',
    type: 'agonist',
    exercise1: 'Banded Hip Thrust',
    exercise2: 'Barbell Romanian Deadlift',
    coachNote: 'Glute activation before hinge pattern for posterior chain sessions.',
    bestFor: ['muscleBuilding', 'fatLoss'],
  },
  SS19: {
    id: 'SS19',
    name: 'Bodyweight Glute Bridge plus Barbell Hip Thrust',
    type: 'agonist',
    exercise1: 'Bodyweight Glute Bridge',
    exercise2: 'Barbell Hip Thrust',
    coachNote: 'Bodyweight bridge primes glutes before loaded thrust.',
    bestFor: ['muscleBuilding', 'fatLoss'],
  },
  SS20: {
    id: 'SS20',
    name: 'Romanian Deadlift plus Lying Leg Curl',
    type: 'agonist',
    exercise1: 'Barbell Romanian Deadlift',
    exercise2: 'Lying Leg Curl',
    coachNote: 'RDL trains hamstring hip extension; leg curl trains knee flexion—complete hamstring superset.',
    bestFor: ['muscleBuilding'],
  },
  SS21: {
    id: 'SS21',
    name: 'Barbell Hip Thrust plus Banded Glute Bridge',
    type: 'agonist',
    exercise1: 'Barbell Hip Thrust',
    exercise2: 'Banded Glute Bridge',
    coachNote: 'Hip thrust for maximum load; banded glute bridge for pump and blood flow with muscle already activated. Use band above knees on glute bridge when prescribed.',
    bestFor: ['fatLoss', 'muscleBuilding'],
  },
  SS22: {
    id: 'SS22',
    name: 'Dumbbell Bulgarian Split Squat plus Dumbbell Walking Lunge',
    type: 'agonist',
    exercise1: 'Dumbbell Bulgarian Split Squat',
    exercise2: 'Dumbbell Walking Lunge',
    coachNote: 'Single-leg quad and glute volume in one pairing.',
    bestFor: ['muscleBuilding', 'athletic'],
  },
  SS23: {
    id: 'SS23',
    name: 'Dumbbell Lateral Raise plus Barbell Overhead Press Standing',
    type: 'preExhaust',
    exercise1: 'Dumbbell Lateral Raise',
    exercise2: 'Barbell Overhead Press Standing',
    coachNote: 'Isolate delts before strict pressing.',
    bestFor: ['muscleBuilding'],
  },
  SS24: {
    id: 'SS24',
    name: 'Dumbbell Chest Fly plus Barbell Incline Press',
    type: 'preExhaust',
    exercise1: 'Dumbbell Chest Fly',
    exercise2: 'Barbell Incline Press',
    coachNote: 'Stretch-mediated fly before incline barbell work.',
    bestFor: ['muscleBuilding'],
  },
  SS25: {
    id: 'SS25',
    name: 'Seated Leg Extension Band plus Dumbbell Goblet Squat',
    type: 'preExhaust',
    exercise1: 'Seated Leg Extension Band',
    exercise2: 'Dumbbell Goblet Squat',
    coachNote: 'Quad isolation before squat pattern; choose conservative squat load.',
    bestFor: ['muscleBuilding'],
  },
  SS26: {
    id: 'SS26',
    name: 'Banded Face Pull plus Chest Supported Dumbbell Row',
    type: 'preExhaust',
    exercise1: 'Banded Face Pull',
    exercise2: 'Chest Supported Dumbbell Row',
    coachNote: 'Rear delt and cuff activation before heavy rowing.',
    bestFor: ['muscleBuilding'],
  },
  SS27: {
    id: 'SS27',
    name: 'Banded Lat Pulldown plus Seated Cable Row Close Grip',
    type: 'preExhaust',
    exercise1: 'Banded Lat Pulldown',
    exercise2: 'Seated Cable Row Close Grip',
    coachNote: 'Lat pre-fatigue before row; use straight-arm pulldown style on first move if programmed.',
    bestFor: ['muscleBuilding'],
  },
  SS28: {
    id: 'SS28',
    name: 'Bodyweight Glute Bridge plus Barbell Sumo Deadlift',
    type: 'preExhaust',
    exercise1: 'Bodyweight Glute Bridge',
    exercise2: 'Barbell Sumo Deadlift',
    coachNote: 'Glute activation before wide-stance pulling.',
    bestFor: ['muscleBuilding', 'strength'],
  },
  SS29: {
    id: 'SS29',
    name: 'Banded Overhead Tricep Extension plus Dumbbell Push Press',
    type: 'preExhaust',
    exercise1: 'Banded Overhead Tricep Extension',
    exercise2: 'Dumbbell Push Press',
    coachNote: 'Triceps isolation before explosive press.',
    bestFor: ['muscleBuilding', 'athletic'],
  },
  SS30: {
    id: 'SS30',
    name: 'Banded Bicep Curl plus Dumbbell Single Arm Row',
    type: 'preExhaust',
    exercise1: 'Banded Bicep Curl',
    exercise2: 'Dumbbell Single Arm Row',
    coachNote: 'Arm flexors before heavy single-arm rows.',
    bestFor: ['muscleBuilding'],
  },
  SS31: {
    id: 'SS31',
    name: 'Barbell Bench Press plus Dumbbell Chest Fly',
    type: 'postExhaust',
    exercise1: 'Barbell Bench Press',
    exercise2: 'Dumbbell Chest Fly',
    coachNote: 'Heavy bench then fly finisher for chest.',
    bestFor: ['muscleBuilding'],
  },
  SS32: {
    id: 'SS32',
    name: 'Barbell Back Squat plus Seated Leg Extension Band',
    type: 'postExhaust',
    exercise1: 'Barbell Back Squat',
    exercise2: 'Seated Leg Extension Band',
    coachNote: 'Compound squat then quad isolation finisher.',
    bestFor: ['muscleBuilding'],
  },
  SS33: {
    id: 'SS33',
    name: 'Barbell Bent Over Row plus Banded Lat Pulldown',
    type: 'postExhaust',
    exercise1: 'Barbell Bent Over Row',
    exercise2: 'Banded Lat Pulldown',
    coachNote: 'Heavy row then lat finisher with different vector.',
    bestFor: ['muscleBuilding'],
  },
  SS34: {
    id: 'SS34',
    name: 'Barbell Overhead Press Standing plus Dumbbell Lateral Raise',
    type: 'postExhaust',
    exercise1: 'Barbell Overhead Press Standing',
    exercise2: 'Dumbbell Lateral Raise',
    coachNote: 'Press then lateral raise for delt volume.',
    bestFor: ['muscleBuilding'],
  },
  SS35: {
    id: 'SS35',
    name: 'Barbell Romanian Deadlift plus Lying Hamstring Curl',
    type: 'postExhaust',
    exercise1: 'Barbell Romanian Deadlift',
    exercise2: 'Lying Hamstring Curl',
    coachNote: 'Heavy hinge then hamstring knee-flexion finisher.',
    bestFor: ['muscleBuilding'],
  },
  SS36: {
    id: 'SS36',
    name: 'Pull-Up plus Dumbbell Hammer Curl',
    type: 'postExhaust',
    exercise1: 'Pull-Up',
    exercise2: 'Dumbbell Hammer Curl',
    coachNote: 'Vertical pull then arm finisher; use band-assisted or machine assist if needed.',
    bestFor: ['muscleBuilding'],
  },
  SS37: {
    id: 'SS37',
    name: 'Barbell Hip Thrust plus Bodyweight Glute Bridge',
    type: 'postExhaust',
    exercise1: 'Barbell Hip Thrust',
    exercise2: 'Bodyweight Glute Bridge',
    coachNote: 'Loaded thrust then bodyweight burn-out.',
    bestFor: ['muscleBuilding', 'fatLoss'],
  },
  SS38: {
    id: 'SS38',
    name: 'Barbell Sumo Deadlift plus Banded Good Morning',
    type: 'postExhaust',
    exercise1: 'Barbell Sumo Deadlift',
    exercise2: 'Banded Good Morning',
    coachNote: 'Heavy pull then hinge accessory with band.',
    bestFor: ['muscleBuilding', 'strength'],
  },
  SS39: {
    id: 'SS39',
    name: 'Barbell Back Squat heavy plus Jump Squat',
    type: 'contrast',
    exercise1: 'Barbell Back Squat',
    exercise2: 'Jump Squat',
    coachNote: 'Heavy squat activates fast-twitch motor units; bodyweight jump squat uses heightened neural drive for greater vertical power; rest 10–15 seconds between movements only.',
    bestFor: ['athletic'],
  },
  SS40: {
    id: 'SS40',
    name: 'Barbell Romanian Deadlift heavy plus Kettlebell Swing Two Hand',
    type: 'contrast',
    exercise1: 'Barbell Romanian Deadlift',
    exercise2: 'Kettlebell Swing Two Hand',
    coachNote: 'Heavy RDL loads posterior chain maximally; KB swing after uses same hip extension pattern explosively, neural drive from RDL makes swing more powerful.',
    bestFor: ['athletic'],
  },
  SS41: {
    id: 'SS41',
    name: 'Barbell Bench Press heavy plus Medicine Ball Chest Pass Against Wall',
    type: 'contrast',
    exercise1: 'Barbell Bench Press',
    exercise2: 'Medicine Ball Chest Pass Against Wall',
    coachNote: 'Heavy bench activates pec fast-twitch fibres; med ball chest pass expresses that activation as horizontal pressing power.',
    bestFor: ['athletic', 'strength'],
  },
  SS42: {
    id: 'SS42',
    name: 'Box Jump plus Broad Jump',
    type: 'contrast',
    exercise1: 'Box Jump',
    exercise2: 'Broad Jump',
    coachNote: 'Vertical then horizontal power expression in one contrast block.',
    bestFor: ['athletic'],
  },
  SS43: {
    id: 'SS43',
    name: 'Kettlebell Snatch plus Jump Squat',
    type: 'contrast',
    exercise1: 'Kettlebell Snatch',
    exercise2: 'Jump Squat',
    coachNote: 'Ballistic overhead work followed by lower-body plyometrics; advanced only.',
    bestFor: ['athletic'],
  },
  SS44: {
    id: 'SS44',
    name: 'Barbell Sumo High Pull plus Med Ball Squat Plus Chest Pass',
    type: 'contrast',
    exercise1: 'Barbell Sumo High Pull',
    exercise2: 'Med Ball Squat Plus Chest Pass',
    coachNote: 'Olympic pull variation then full-body power throw from squat.',
    bestFor: ['athletic'],
  },
  SS45: {
    id: 'SS45',
    name: 'Barbell Overhead Press heavy plus Dumbbell Push Press',
    type: 'contrast',
    exercise1: 'Barbell Overhead Press Standing',
    exercise2: 'Dumbbell Push Press',
    coachNote: 'Strict press at maximum load, push press after allows neurally activated shoulders to express power with assistance; push press ~20–30% lighter.',
    bestFor: ['athletic', 'strength'],
  },
  SS46: {
    id: 'SS46',
    name: 'Trap Bar Deadlift heavy plus Box Jump',
    type: 'contrast',
    exercise1: 'Trap Bar Deadlift',
    exercise2: 'Box Jump',
    coachNote: 'Most extensively researched contrast pairing in sport science for developing athletic power; substitute Barbell Sumo Deadlift if trap bar unavailable.',
    bestFor: ['athletic'],
  },
  SS47: {
    id: 'SS47',
    name: 'Kettlebell Swing 20 reps plus Farmers Carry 40m',
    type: 'functionalComplex',
    exercise1: 'Kettlebell Swing Two Hand',
    exercise2: 'Kettlebell Farmers Carry',
    coachNote: 'Swings build explosive hip power; carry maintains intensity under loaded grip and core demand.',
    bestFor: ['fatLoss', 'athletic'],
  },
  SS48: {
    id: 'SS48',
    name: 'Wall Ball plus Rowing Machine 500m',
    type: 'conditioning',
    exercise1: 'Wall Ball',
    exercise2: 'Rowing Machine',
    coachNote: 'High-threshold full-body ball work into sustained rowing; pace the row.',
    bestFor: ['athletic'],
  },
  SS49: {
    id: 'SS49',
    name: 'Burpee to Pull Up plus Box Jump',
    type: 'functionalComplex',
    exercise1: 'Burpee to Pull Up',
    exercise2: 'Box Jump',
    coachNote: 'Gymnastics-strength plus plyometrics for mixed-modal fitness.',
    bestFor: ['athletic'],
  },
  SS50: {
    id: 'SS50',
    name: 'Dumbbell Devil Press plus Ski Erg',
    type: 'functionalComplex',
    exercise1: 'Dumbbell Devil Press',
    exercise2: 'Ski Erg',
    coachNote: 'Race-style coupling of full-body DB work with ski erg conditioning.',
    bestFor: ['fatLoss'],
  },
  SS51: {
    id: 'SS51',
    name: 'Wall Ball 20 reps plus Ski Erg 250m',
    type: 'conditioning',
    exercise1: 'Wall Ball',
    exercise2: 'Ski Erg',
    coachNote: 'Wall ball and ski erg paired back to back replicate race demand of moving station to station with minimal recovery.',
    bestFor: ['athletic'],
  },
  SS52: {
    id: 'SS52',
    name: 'Suitcase Carry plus Sandbag Carry Shoulder or Bear Hug',
    type: 'functionalComplex',
    exercise1: 'Suitcase Carry',
    exercise2: 'Sandbag Carry Shoulder or Bear Hug',
    coachNote: 'Unilateral and sandbag carries for core and grip endurance.',
    bestFor: ['athletic', 'strength'],
  },
  SS53: {
    id: 'SS53',
    name: 'Sled Push 25m plus Sled Pull Rope or Strap 25m',
    type: 'conditioning',
    exercise1: 'Sled Push',
    exercise2: 'Sled Pull Rope or Strap',
    coachNote: 'Sled push and pull back to back one load two directions no rest; directly mimics race sled stations.',
    bestFor: ['athletic'],
  },
  SS54: {
    id: 'SS54',
    name: 'Barbell Thruster plus Assault Bike All Out Intervals',
    type: 'functionalComplex',
    exercise1: 'Barbell Thruster',
    exercise2: 'Assault Bike All Out Intervals',
    coachNote: 'Barbell conditioning into bike sprint; use short work windows.',
    bestFor: ['fatLoss', 'athletic'],
  },
  SS55: {
    id: 'SS55',
    name: 'Med Ball Burpee to Slam plus Rowing Machine',
    type: 'functionalComplex',
    exercise1: 'Med Ball Burpee to Slam',
    exercise2: 'Rowing Machine',
    coachNote: 'Slam burpee density into rowing; adjust distance or strokes to session goal.',
    bestFor: ['fatLoss'],
  },
  SS56: {
    id: 'SS56',
    name: 'Sandbag Carry plus Dumbbell Walking Lunge',
    type: 'functionalComplex',
    exercise1: 'Sandbag Carry Shoulder or Bear Hug',
    exercise2: 'Dumbbell Walking Lunge',
    coachNote: 'Loaded carry transitions into lunging for legs under fatigue.',
    bestFor: ['athletic'],
  },
  SS57: {
    id: 'SS57',
    name: 'Sprint Intervals 10 to 40m plus Active Recovery Walk',
    type: 'functionalComplex',
    exercise1: 'Sprint Intervals 10 to 40m',
    exercise2: 'Bodyweight Glute Bridge',
    coachNote: 'Sprint intervals with walk-back recovery between reps; optional second movement is easy active recovery only.',
    bestFor: ['athletic', 'fatLoss'],
  },
  SS58: {
    id: 'SS58',
    name: 'Med Ball Bear Crawl Push plus Plank Hold',
    type: 'functionalComplex',
    exercise1: 'Med Ball Bear Crawl Push',
    exercise2: 'Plank Hold',
    coachNote: 'Anti-extension work in two forms for core endurance.',
    bestFor: ['fatLoss', 'athletic'],
  },
  SS59: {
    id: 'SS59',
    name: 'Dumbbell Man Maker plus Kettlebell Swing Two Hand',
    type: 'functionalComplex',
    exercise1: 'Dumbbell Man Maker',
    exercise2: 'Kettlebell Swing Two Hand',
    coachNote: 'Full-body DB complex plus hip power; advanced conditioning.',
    bestFor: ['fatLoss', 'athletic'],
  },
  SS60: {
    id: 'SS60',
    name: 'Kettlebell Clean Plus Jerk plus Wall Ball',
    type: 'conditioning',
    exercise1: 'Kettlebell Clean Plus Jerk',
    exercise2: 'Wall Ball',
    coachNote: 'Olympic lift pattern endurance into wall ball for race-specific density.',
    bestFor: ['athletic'],
  },
}
